body {
    font-family: 'Roboto', Arial, sans-serif;
    text-align: center;
    background: linear-gradient(to bottom, rgba(255, 255, 255, 0.8), rgba(255, 244, 244, 0.9)), 
                url('https://images.pexels.com/photos/5622219/pexels-photo-5622219.jpeg') no-repeat center center;
    background-size: cover;
    margin: 0;
    padding: 0;
    color: #333;
    background-attachment: fixed;
}

.container {
    max-width: 400px;
    margin: 50px auto;
    padding: 25px;
    background: rgba(255, 255, 255, 0.95);
    border-radius: 20px;
    box-shadow: 0 6px 20px rgba(0, 0, 0, 0.4);
    position: relative;
    z-index: 1;
}

input {
    display: block;
    width: 90%;
    margin: 15px auto;
    padding: 15px;
    font-size: 18px;
    border: 2px solid #4CAF50;
    border-radius: 12px;
    box-shadow: inset 0 2px 6px rgba(0, 0, 0, 0.1);
    transition: border-color 0.3s, box-shadow 0.3s;
}

input:focus {
    outline: none;
    border-color: #66bb6a;
    box-shadow: 0 0 8px rgba(102, 187, 106, 0.5);
}

button {
    padding: 12px 25px;
    font-size: 18px;
    font-weight: bold;
    margin-top: 20px;
    cursor: pointer;
    background: linear-gradient(to right, #66bb6a, #388e3c);
    color: white;
    border: none;
    border-radius: 25px;
    transition: transform 0.3s, background-color 0.3s ease;
    text-transform: uppercase;
}

button:hover {
    transform: translateY(-3px);
    background-color: #2c6b2f;
}

h1 {
    color: #388e3c;
    font-size: 32px;
    font-weight: bold;
    margin-bottom: 20px;
}

#result, #advice {
    margin-top: 20px;
    font-size: 20px;
    color: #444;
    font-weight: bold;
    font-style: italic;
}

footer {
    margin-top: 30px;
    font-size: 14px;
    color: #666;
    opacity: 0.8;
    font-style: italic;
}

body::before {
    content: "";
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: url('https://images.pexels.com/photos/5622219/pexels-photo-5622219.jpeg');
    background-repeat: no-repeat;
    background-size: cover;
    background-position: center;
    z-index: -1;
    opacity: 0.4;
}
